ckan/datapusher

- datapusher/jobs.py
As per #46:
It is very easy to create column names that include spaces, in particular when hand-typing CSV data:
my field, my other field, a third field
value one, value two, value three
This will create fields named " my other field" and " a third field". Having field names that start/end with spaces causes a lot of complications, because some code strips the field names, while others don't. This is particularly true when using third party libraries, and parsing text-representations of strings such as the sort string "my field ASC, my other field DESC", etc.
See for instance: https://github.com/ckan/ckan/issues/1970
Given that there is no practical use for having field names that start or end with spaces (these will be just as confusing to humans as they are to machines), I suggest the …
> Strip column names

- datapusher/jobs.py
- doc/using.rst
The default is 10mb, but this PR allows a larger (or smaller)
value to be specified in the datapusher_settings.py file.
Complete with documentation
This should close #79
> Allows configuration of maximum file size to be configured.

- datapusher/jobs.py
Some headers might have been converted from strings to floats, for example because there were no headers in the first place. It is important to continue here so that an actual failure is emitted and reported by the CKAN itself.
> Prevent crash on non-string headers

- doc/development.rst
Runing Ubuntu 14.04 got an error when installing python requirements.
When installing lxml an error was given asking to make sure development packages of libxml2 and libxslt are installed.
> Added missing package zlib1g-dev required to install python requirements.

- doc/deployment.rst
There was an end parenthesis that should not be there.
> Fixed syntax error on `cp` of datapusher.conf

- datapusher/jobs.py
Using getdefaultlocale() will get the default system locale, while getlocale() always returns (None, None)
> Use getdefaultlocale() to get the current locale

- datapusher/jobs.py
When you update a resource with the `resource_update` or `resource_patch` API, the datapusher attempts to re-run on the /datastore/dump URL which is by default not a valid URL (i.e. "/datastore/dump/adab91ac-7c08-4837-aca1-31e8efcd9124").
> Check for datastore url_type

- datapusher/jobs.py
When datapusher suffers an error doing a request (as is so common), the response is now logged. e.g.
`HTTPError: CKAN DataStore bad response. Status code: 409 Conflict. At: https://energydata.info/api/3/action/datastore_create. status=409 url=https://energydata.info/api/3/action/datastore_create response={"help": "https://energydata.info/api/3/action/help_show?name=datastore_create", "success": false, "error": {"records": ["row \"1\" has extra keys \"The wind measurement campaign that has generated this data was commissioned by The World Bank with funding from the Energy Sector Management Assistance Program (ESMAP). The data is made freely available under The World Bank?s open data policy.\""], "__type": "Validation Error"}}`
whereas previously it just showed `HTTP Error`, or with #119 it …
> Better error logs

- datapusher/jobs.py
In jobs, we have unicode literals so that `'{0}.{1}'.format(lang, encoding)`
is a unicode string in Python 2. This is causing problem with an old
version of Python's locale module (that in Python 2.7.5 on RedHat 7.2 for
instance) which would type-check this argument against basestring (see https://hg.python.org/cpython/file/v2.7.5/Lib/locale.py#l532 for the old version and https://hg.python.org/cpython/rev/7841e9b614eb for the fix).
So use pass the `locale` information as a tuple which should work in any Python2.7 version.
> Fix call to locale.setlocale in jobs module for old Python 2.7

- requirements.txt
Adding this extras-option to Requests will in particular make sure that certifi-package is used, if available. That way, a carefully curated collection of Root Certificates will be supported when checking for SSL verification.
PR #117 was accidentially closed. Sorry for the confusion it may cause.
> add security requirements-to-datapusher

- requirements.txt
This provides this fix: https://github.com/ckan/ckan-service-provider/pull/32
so that datapusher works with CKAN 2.7.
Fixes #124
> Use the latest version of ckanserviceprovider

- doc/using.rst
This advice to use requests in this way is reliable in my experience, and much safer than turning off the SSL cert check.
> Fix SSL problems with requests[security]

- datapusher/jobs.py
- tests/test_acceptance.py
This is important if the server did not provide the Content-Length
header in the response, but you still want to discard files, that are
too large.
> Check MAX_CONTENT_LENGTH against downloaded file

- datapusher/jobs.py
- doc/using.rst
- tests/test_acceptance.py
It seems a no-brainer to use requests instead of urllib2 for this key step of downloading the data file that gets pushed because requests is superior in lots of ways.
[Since python 2.7.9, urllib2 went from not verifying certificates at all to verifying them against the OS's built-in list](https://stackoverflow.com/a/28325763). My experience of the latter is that it goes out of date and even big sites like github.com start getting rejected. Requests handles this much better imo because it updates more frequently via the certifi python module (installed with `requests[security]`. I've used this in ckanext-archiver in a similar for several years with success, but successfully checking HTTPS certs.
I've checked the tests pass, but it's not tried in production or battle-hardened, so could do …
> Use requests to download files instead of urllib2 AND extend SSL_VERIFY option to these requests (for testing)

- datapusher/jobs.py
- doc/using.rst
As discussed here: https://github.com/ckan/datapusher/pull/109#discussion_r102938501
we check if SSL_VERIFY by comparing it to several possibilities of assigning it to false. ('False', 'FALSE', '0', False and 0)
This would fix https://github.com/ckan/datapusher/issues/149
> add False and 0 as possible values for SSL_VERIFY-option

- datapusher/jobs.py
- tests/test_unit.py
Compatibility with: https://github.com/ckan/ckan/pull/4473.
Now when it pushes the last chunk it sets calculate_record_count=True and datastore will do an ANALYZE, which stores a count of the rows, so that when a user previews the resource this count can be used instead of a more expensive SELECT COUNT(*) at load-time.
Together these 2 PRs will speed up viewing large resources. Nothing breaks if you update one but not the other.
> Calculate record count

- deployment/datapusher.wsgi
https://docs.python.org/3.3/whatsnew/3.0.html?highlight=execfile#builtins
> Removed execfile(). Instead of execfile(fn) use exec(open(fn).read()).
> fix: py3 support

- datapusher/main.py
Argparse has removed the `type=file` support in Py3.
https://docs.python.org/3/library/argparse.html#type
Using six to validate the python version and then using argparse accordingly.
> Py3 argparser fix

- datapusher/jobs.py
The encoding issue was due to Latin char that is converted by the `requests` module `iter_content`.
Fixes ckan/ckan#5434
> Prevent wrong utf-8 encoding

- datapusher/jobs.py
Resolving 409 error for https://github.com/okfn/ckanext-unhcr/issues/304
> `requests.post` does not use `params`

- datapusher/jobs.py
Add the ability to configure the way datapusher reads and inserts data into CKAN by reading CHUNK_SIZE, CHUNK_INSERT_ROWS and DOWNLOAD_TIMEOUT from config so that they can be loaded in during runtime through environment variables.
> Read chunk size, chunk inserts and timeouts from config

- README.md
- deployment/datapusher_settings.py
Currently there is no way of setting up the logging without modifying a file in the working tree of this repository. That means that maintaining datapusher up to date requires stashing, pulling and popping the stash instead of having a clean repository all the time.
This PR allows to read `LOG_FILE` and `STDERR` from environment variables and documents the new variables in the readme.
This PR actually requires https://github.com/ckan/ckan-service-provider/pull/56 to be merged, a version of it released and the `requirements.txt` file to be updated.
> Allow to setup logging via environment variables
